<?php

namespace ContainerLPlVYYE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGentlePuppyRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\GentlePuppyRepository' shared autowired service.
     *
     * @return \App\Repository\GentlePuppyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\GentlePuppyRepository'] = new \App\Repository\GentlePuppyRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
