<?php

namespace ContainerLPlVYYE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakeupRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MakeupRepository' shared autowired service.
     *
     * @return \App\Repository\MakeupRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MakeupRepository'] = new \App\Repository\MakeupRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
