<?php

namespace ContainerLPlVYYE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderValidateControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\OrderValidateController' shared autowired service.
     *
     * @return \App\Controller\OrderValidateController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\OrderValidateController'] = $instance = new \App\Controller\OrderValidateController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\OrderValidateController', $container));

        return $instance;
    }
}
