<?php

namespace ContainerLPlVYYE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubcategoryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SubcategoryRepository' shared autowired service.
     *
     * @return \App\Repository\SubcategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SubcategoryRepository'] = new \App\Repository\SubcategoryRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
