<?php

namespace ContainerLPlVYYE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubcategoryCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\SubcategoryCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\SubcategoryCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\SubcategoryCrudController'] = $instance = new \App\Controller\Admin\SubcategoryCrudController();

        $instance->setContainer(($container->privates['.service_locator.7Gh9pQb'] ?? $container->load('get_ServiceLocator_7Gh9pQbService'))->withContext('App\\Controller\\Admin\\SubcategoryCrudController', $container));

        return $instance;
    }
}
