<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDsYypRP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDsYypRP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDsYypRP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDsYypRP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDsYypRP\App_KernelDevDebugContainer([
    'container.build_hash' => 'DsYypRP',
    'container.build_id' => '76938b7f',
    'container.build_time' => 1613042166,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDsYypRP');
